
export const searchComicsActions = {
    SEARCH_COMICS_PENDING: "SEARCH_COMICS_PENDING",
    SEARCH_COMICS_ERROR: "SEARCH_COMICS_ERROR",
    SEARCH_COMICS_SUCCESS: "SEARCH_COMICS_SUCCESS"
}

export const comicsActions = {
    GET_COMICS_PENDING: "GET_COMICS_PENDING",
    GET_COMICS_ERROR: "GET_COMICS_ERROR",
    GET_COMICS_SUCCESS: "GET_COMICS_SUCCESS",
}

export const comicActions = {
    GET_COMIC_PENDING: "GET_COMIC_PENDING",
    GET_COMIC_ERROR: "GET_COMIC_ERROR",
    GET_COMIC_SUCCESS: "GET_COMIC_SUCCESS"
}
