
export const searchComicsActions = {
    SEARCH_COMICS_PENDING: 'SEARCH_COMICS_PENDING',
    SEARCH_COMICS_ERROR: 'SEARCH_COMICS_ERROR',
    SEARCH_COMICS_SUCCESS: 'SEARCH_COMICS_SUCCESS'
}

export const comicsActions = {
    GET_COMICS_PENDING: 'GET_COMICS_PENDING',
    GET_COMICS_ERROR: 'GET_COMICS_ERROR',
    GET_COMICS_SUCCESS: 'GET_COMICS_SUCCESS',
}

export const comicActions = {
    GET_FAVOURITE_COMICS_PENDING: 'GET_FAVOURITE_COMICS_PENDING',
    GET_FAVOURITE_COMICS_ERROR: 'GET_FAVOURITE_COMICS_ERROR',
    GET_FAVOURITE_COMICS_SUCCESS: 'GET_FAVOURITE_COMICS_SUCCESS',
    FAVOURITE_COMIC_PENDING: 'FAVOURITE_COMIC_PENDING',
    FAVOURITE_COMIC_ERROR: 'FAVOURITE_COMIC_ERROR',
    FAVOURITE_COMIC_SUCCESS: 'FAVOURITE_COMIC_SUCCESS',
    UNFAVOURITE_COMIC_PENDING: 'UNFAVOURITE_COMIC_PENDING',
    UNFAVOURITE_COMIC_ERROR: 'UNFAVOURITE_COMIC_ERROR',
    UNFAVOURITE_COMIC_SUCCESS: 'UNFAVOURITE_COMIC_SUCCESS',
}
